services:
  - type: web
    name: vittmoney-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: vittmoney-ml
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000 --workers 1
    rootDir: ml
    envVars:
      - key: TRANSFORMERS_NO_ADVISORY_WARNINGS
        value: "1"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: OMP_NUM_THREADS
        value: "1"
